### ISSUE TITLE
make install does not install manpage

### ISSUE THREAD

**Issue by rofl0r** [wiire-a/pixiewps#82]
in order to fix it, manpage should be moved to src

or even better, the top level makefile actually becomes the real makefile and builds stuff in src
you could add a target like "make openwrt" which runs make -f Makefile.openwrt

**Comment by wiire-a** [comment]
The content of the man page is pretty much identical to the one `pixiewps --help` displays. The man page is probably nicer but if someone really wants to install it can do so manually, and I'm sure distro maintainers will package it if they want to.

About the OpenWrt Makefile I'm still unsure what the "best strategy" would be. If it gets included into their packages repository I'll probably move it somewhere else. Either in a subfolder or a separate repository.

**Comment by nasserr** [comment]
Hi Wiire, I want to contribute sometimes as a developer on PixieWps, can I ? :)

**Comment by nasserr** [comment]
Can't without forking

**Comment by soxrok2212** [comment]
What's the issue with forking?

**Comment by wiire-a** [comment]
I'll take a break a break for a while because of stuff I left behind IRL. Full-on development will be resumed in March.

In the meantime @rofl0r can review and submit patches if he wishes.

Also, @rofl0r [pixiewps 1.4.1](https://github.com/openwrt/packages/blob/master/net/pixiewps/Makefile) and [Reaver 1.6.3](https://github.com/openwrt/packages/blob/master/net/reaver/Makefile) made it to the OpenWrt repository. See: https://github.com/openwrt/packages/issues/2872

If anyone here that has OpenWrt can test them that would be great. Thanks.

**Comment by nasserr** [comment]
I can't pull without forking, I made a pull request in a fork

**Comment by kimocoder** [comment]
Are you referring to [this](https://github.com/nasserr/pixiewps/commit/38bf275714b0bacc0f76201d595d59be5096e952)

https://github.com/nasserr/pixiewps/commit/38bf275714b0bacc0f76201d595d59be5096e952

**Comment by rofl0r** [comment]
@nasserr  could you please stop hijacking this thread for your own purposes. if you think there is a problem, open your own issue. this here is about manpage installation.

**Comment by wiire-a** [comment]
Done with 19def8c and d45d1c3.
